version: "3.9"

services:

  consul:
    image: bitnami/consul
    container_name: "consul"
    ports:
      - "8500:8500"
    command: "consul agent -dev -ui -client=0.0.0.0"

  postgres:
    image: postgres:16.2
    container_name: "postgres"
    environment:
      POSTGRES_DB: university
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"


networks:
  default:
    name: network
    driver: bridge

